name: CI

on:
    push:
        branches: [ master ]
    pull_request: ~

jobs:
    tests:
        name: Tests
        runs-on: "ubuntu-20.04"
        timeout-minutes: 10

        strategy:
            matrix:
                php:
                    - '7.3'
                    - '7.4'

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - uses: "ramsey/composer-install@v1"

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Run test suite
              run: composer run-script test
